Stick to setup-buildx-action
Stick to older setup-buildx-action after ARM build breaks with

error: failed to list workers: Unavailable: connection error: desc = "transport: Error while dialing: dial unix /run/buildkit/buildkitd.sock: connect: no such file or directory"